'''
            Archivo generado desde: https://github.com/xbmc/xbmc/blob/master/xbmc/input/XBMC_keytable.cpp
'''

from Keysym import *
from Vkeys import *
from KodiAddonIDE.KodiStubs.TkinterKeys import *

XBMCK,  VK,  XBMCVK,  NAME = range(4)
_xbmck, _vk, _xbmcvk, _name = [], [], [], []

_add = lambda a, b, c, d: (_xbmck.append(a), _vk.append(b), _xbmcvk.append(c), _name.append(d))

def lookup(lookup_value, indx):
	indx = max(0, min(3, indx))
	colValues = (_xbmck, _vk, _xbmcvk, _name)[indx]
	try:
		npos = colValues.index(lookup_value)
	except:
		return None
	return _xbmck[npos], _vk[npos], _xbmcvk[npos], _name[npos]


_add(          XBMCK_BACKSPACE,           VK_BACKSPACE,                XBMCVK_BACK,           "backspace")
_add(                XBMCK_TAB,                 VK_TAB,                 XBMCVK_TAB,                 "tab")
_add(             XBMCK_RETURN,              VK_RETURN,              XBMCVK_RETURN,              "return")
_add(             XBMCK_ESCAPE,              VK_ESCAPE,              XBMCVK_ESCAPE,              "escape")
_add(                  XBMCK_0,                   VK_0,                   XBMCVK_0,                "zero")
_add(                  XBMCK_1,                   VK_1,                   XBMCVK_1,                 "one")
_add(                  XBMCK_2,                   VK_2,                   XBMCVK_2,                 "two")
_add(                  XBMCK_3,                   VK_3,                   XBMCVK_3,               "three")
_add(                  XBMCK_4,                   VK_4,                   XBMCVK_4,                "four")
_add(                  XBMCK_5,                   VK_5,                   XBMCVK_5,                "five")
_add(                  XBMCK_6,                   VK_6,                   XBMCVK_6,                 "six")
_add(                  XBMCK_7,                   VK_7,                   XBMCVK_7,               "seven")
_add(                  XBMCK_8,                   VK_8,                   XBMCVK_8,               "eight")
_add(                  XBMCK_9,                   VK_9,                   XBMCVK_9,                "nine")
_add(                  XBMCK_a,                   VK_a,                   XBMCVK_A,                   "a")
_add(                  XBMCK_b,                   VK_b,                   XBMCVK_B,                   "b")
_add(                  XBMCK_c,                   VK_c,                   XBMCVK_C,                   "c")
_add(                  XBMCK_d,                   VK_d,                   XBMCVK_D,                   "d")
_add(                  XBMCK_e,                   VK_e,                   XBMCVK_E,                   "e")
_add(                  XBMCK_f,                   VK_f,                   XBMCVK_F,                   "f")
_add(                  XBMCK_g,                   VK_g,                   XBMCVK_G,                   "g")
_add(                  XBMCK_h,                   VK_h,                   XBMCVK_H,                   "h")
_add(                  XBMCK_i,                   VK_i,                   XBMCVK_I,                   "i")
_add(                  XBMCK_j,                   VK_j,                   XBMCVK_J,                   "j")
_add(                  XBMCK_k,                   VK_k,                   XBMCVK_K,                   "k")
_add(                  XBMCK_l,                   VK_l,                   XBMCVK_L,                   "l")
_add(                  XBMCK_m,                   VK_m,                   XBMCVK_M,                   "m")
_add(                  XBMCK_n,                   VK_n,                   XBMCVK_N,                   "n")
_add(                  XBMCK_o,                   VK_o,                   XBMCVK_O,                   "o")
_add(                  XBMCK_p,                   VK_p,                   XBMCVK_P,                   "p")
_add(                  XBMCK_q,                   VK_q,                   XBMCVK_Q,                   "q")
_add(                  XBMCK_r,                   VK_r,                   XBMCVK_R,                   "r")
_add(                  XBMCK_s,                   VK_s,                   XBMCVK_S,                   "s")
_add(                  XBMCK_t,                   VK_t,                   XBMCVK_T,                   "t")
_add(                  XBMCK_u,                   VK_u,                   XBMCVK_U,                   "u")
_add(                  XBMCK_v,                   VK_v,                   XBMCVK_V,                   "v")
_add(                  XBMCK_w,                   VK_w,                   XBMCVK_W,                   "w")
_add(                  XBMCK_x,                   VK_x,                   XBMCVK_X,                   "x")
_add(                  XBMCK_y,                   VK_y,                   XBMCVK_Y,                   "y")
_add(                  XBMCK_z,                   VK_z,                   XBMCVK_Z,                   "z")
_add(              XBMCK_SPACE,               VK_SPACE,               XBMCVK_SPACE,               "space")
_add(            XBMCK_EXCLAIM,             VK_EXCLAIM,             XBMCVK_EXCLAIM,             "exclaim")
_add(           XBMCK_QUOTEDBL,            VK_QUOTEDBL,            XBMCVK_QUOTEDBL,         "doublequote")
_add(               XBMCK_HASH,                VK_HASH,                XBMCVK_HASH,                "hash")
_add(             XBMCK_DOLLAR,              VK_DOLLAR,              XBMCVK_DOLLAR,              "dollar")
_add(            XBMCK_PERCENT,             VK_PERCENT,             XBMCVK_PERCENT,             "percent")
_add(          XBMCK_AMPERSAND,           VK_AMPERSAND,           XBMCVK_AMPERSAND,           "ampersand")
_add(              XBMCK_QUOTE,               VK_QUOTE,               XBMCVK_QUOTE,               "quote")
_add(          XBMCK_LEFTPAREN,           VK_LEFTPAREN,           XBMCVK_LEFTPAREN,         "leftbracket")
_add(         XBMCK_RIGHTPAREN,          VK_RIGHTPAREN,          XBMCVK_RIGHTPAREN,        "rightbracket")
_add(           XBMCK_ASTERISK,            VK_ASTERISK,            XBMCVK_ASTERISK,            "asterisk")
_add(               XBMCK_PLUS,                VK_PLUS,                XBMCVK_PLUS,                "plus")
_add(              XBMCK_COMMA,               VK_COMMA,               XBMCVK_COMMA,               "comma")
_add(              XBMCK_MINUS,               VK_MINUS,               XBMCVK_MINUS,               "minus")
_add(             XBMCK_PERIOD,              VK_PERIOD,              XBMCVK_PERIOD,              "period")
_add(              XBMCK_SLASH,               VK_SLASH,               XBMCVK_SLASH,        "forwardslash")
_add(              XBMCK_COLON,               VK_COLON,               XBMCVK_COLON,               "colon")
_add(          XBMCK_SEMICOLON,           VK_SEMICOLON,           XBMCVK_SEMICOLON,           "semicolon")
_add(               XBMCK_LESS,                VK_LESS,                XBMCVK_LESS,            "lessthan")
_add(             XBMCK_EQUALS,              VK_EQUALS,              XBMCVK_EQUALS,              "equals")
_add(            XBMCK_GREATER,             VK_GREATER,             XBMCVK_GREATER,         "greaterthan")
_add(           XBMCK_QUESTION,            VK_QUESTION,            XBMCVK_QUESTION,        "questionmark")
_add(                 XBMCK_AT,                  VK_AT,                  XBMCVK_AT,                  "at")
_add(        XBMCK_LEFTBRACKET,         VK_LEFTBRACKET,         XBMCVK_LEFTBRACKET,   "opensquarebracket")
_add(          XBMCK_BACKSLASH,           VK_BACKSLASH,           XBMCVK_BACKSLASH,           "backslash")
_add(       XBMCK_RIGHTBRACKET,        VK_RIGHTBRACKET,        XBMCVK_RIGHTBRACKET,  "closesquarebracket")
_add(              XBMCK_CARET,               VK_CARET,               XBMCVK_CARET,               "caret")
_add(         XBMCK_UNDERSCORE,          VK_UNDERSCORE,          XBMCVK_UNDERSCORE,           "underline")
_add(          XBMCK_BACKQUOTE,           VK_BACKQUOTE,           XBMCVK_BACKQUOTE,           "leftquote")
_add(          XBMCK_LEFTBRACE,           VK_LEFTBRACE,           XBMCVK_LEFTBRACE,           "openbrace")
_add(               XBMCK_PIPE,                VK_PIPE,                XBMCVK_PIPE,                "pipe")
_add(         XBMCK_RIGHTBRACE,          VK_RIGHTBRACE,          XBMCVK_RIGHTBRACE,          "closebrace")
_add(              XBMCK_TILDE,               VK_TILDE,               XBMCVK_TILDE,               "tilde")
_add(                XBMCK_KP0,                 VK_KP0,             XBMCVK_NUMPAD0,          "numpadzero")
_add(                XBMCK_KP1,                 VK_KP1,             XBMCVK_NUMPAD1,           "numpadone")
_add(                XBMCK_KP2,                 VK_KP2,             XBMCVK_NUMPAD2,           "numpadtwo")
_add(                XBMCK_KP3,                 VK_KP3,             XBMCVK_NUMPAD3,         "numpadthree")
_add(                XBMCK_KP4,                 VK_KP4,             XBMCVK_NUMPAD4,          "numpadfour")
_add(                XBMCK_KP5,                 VK_KP5,             XBMCVK_NUMPAD5,          "numpadfive")
_add(                XBMCK_KP6,                 VK_KP6,             XBMCVK_NUMPAD6,           "numpadsix")
_add(                XBMCK_KP7,                 VK_KP7,             XBMCVK_NUMPAD7,         "numpadseven")
_add(                XBMCK_KP8,                 VK_KP8,             XBMCVK_NUMPAD8,         "numpadeight")
_add(                XBMCK_KP9,                 VK_KP9,             XBMCVK_NUMPAD9,          "numpadnine")
_add(          XBMCK_KP_DIVIDE,           VK_KP_DIVIDE,        XBMCVK_NUMPADDIVIDE,        "numpaddivide")
_add(        XBMCK_KP_MULTIPLY,         VK_KP_MULTIPLY,         XBMCVK_NUMPADTIMES,         "numpadtimes")
_add(           XBMCK_KP_MINUS,            VK_KP_MINUS,         XBMCVK_NUMPADMINUS,         "numpadminus")
_add(            XBMCK_KP_PLUS,             VK_KP_PLUS,          XBMCVK_NUMPADPLUS,          "numpadplus")
_add(           XBMCK_KP_ENTER,            VK_KP_ENTER,         XBMCVK_NUMPADENTER,               "enter")
_add(          XBMCK_KP_PERIOD,           VK_KP_PERIOD,        XBMCVK_NUMPADPERIOD,        "numpadperiod")
_add(       XBMCK_BROWSER_BACK,        VK_BROWSER_BACK,        XBMCVK_BROWSER_BACK,        "browser_back")
_add(    XBMCK_BROWSER_FORWARD,     VK_BROWSER_FORWARD,     XBMCVK_BROWSER_FORWARD,     "browser_forward")
_add(    XBMCK_BROWSER_REFRESH,     VK_BROWSER_REFRESH,     XBMCVK_BROWSER_REFRESH,     "browser_refresh")
_add(       XBMCK_BROWSER_STOP,        VK_BROWSER_STOP,        XBMCVK_BROWSER_STOP,        "browser_stop")
_add(     XBMCK_BROWSER_SEARCH,      VK_BROWSER_SEARCH,      XBMCVK_BROWSER_SEARCH,      "browser_search")
_add(  XBMCK_BROWSER_FAVORITES,   VK_BROWSER_FAVORITES,   XBMCVK_BROWSER_FAVORITES,   "browser_favorites")
_add(       XBMCK_BROWSER_HOME,        VK_BROWSER_HOME,        XBMCVK_BROWSER_HOME,        "browser_home")
_add(        XBMCK_VOLUME_MUTE,         VK_VOLUME_MUTE,         XBMCVK_VOLUME_MUTE,         "volume_mute")
_add(        XBMCK_VOLUME_DOWN,         VK_VOLUME_DOWN,         XBMCVK_VOLUME_DOWN,         "volume_down")
_add(          XBMCK_VOLUME_UP,           VK_VOLUME_UP,           XBMCVK_VOLUME_UP,           "volume_up")
_add(   XBMCK_MEDIA_NEXT_TRACK,    VK_MEDIA_NEXT_TRACK,    XBMCVK_MEDIA_NEXT_TRACK,          "next_track")
_add(   XBMCK_MEDIA_PREV_TRACK,    VK_MEDIA_PREV_TRACK,    XBMCVK_MEDIA_PREV_TRACK,          "prev_track")
_add(         XBMCK_MEDIA_STOP,          VK_MEDIA_STOP,          XBMCVK_MEDIA_STOP,                "stop")
_add(   XBMCK_MEDIA_PLAY_PAUSE,    VK_MEDIA_PLAY_PAUSE,    XBMCVK_MEDIA_PLAY_PAUSE,          "play_pause")
_add(       XBMCK_MEDIA_REWIND,        VK_MEDIA_REWIND,        XBMCVK_MEDIA_REWIND,              "rewind")
_add(  XBMCK_MEDIA_FASTFORWARD,   VK_MEDIA_FASTFORWARD,   XBMCVK_MEDIA_FASTFORWARD,         "fastforward")
_add(        XBMCK_LAUNCH_MAIL,         VK_LAUNCH_MAIL,         XBMCVK_LAUNCH_MAIL,         "launch_mail")
_add(XBMCK_LAUNCH_MEDIA_SELECT, VK_LAUNCH_MEDIA_SELECT, XBMCVK_LAUNCH_MEDIA_SELECT, "launch_media_select")
_add(        XBMCK_LAUNCH_APP1,         VK_LAUNCH_APP1,         XBMCVK_LAUNCH_APP1, "launch_app1_pc_icon")
_add(        XBMCK_LAUNCH_APP2,         VK_LAUNCH_APP2,         XBMCVK_LAUNCH_APP2, "launch_app2_pc_icon")
_add(XBMCK_LAUNCH_FILE_BROWSER, VK_LAUNCH_FILE_BROWSER, XBMCVK_LAUNCH_FILE_BROWSER, "launch_file_browser")
_add(XBMCK_LAUNCH_MEDIA_CENTER, VK_LAUNCH_MEDIA_CENTER, XBMCVK_LAUNCH_MEDIA_CENTER, "launch_media_center")
_add(               XBMCK_PLAY,                VK_PLAY,    XBMCVK_MEDIA_PLAY_PAUSE,          "play_pause")
_add(               XBMCK_STOP,                VK_STOP,          XBMCVK_MEDIA_STOP,                "stop")
_add(             XBMCK_REWIND,              VK_REWIND,        XBMCVK_MEDIA_REWIND,              "rewind")
_add(        XBMCK_FASTFORWARD,         VK_FASTFORWARD,   XBMCVK_MEDIA_FASTFORWARD,         "fastforward")
_add(             XBMCK_RECORD,              VK_RECORD,        XBMCVK_MEDIA_RECORD,              "record")
_add(                 XBMCK_F1,                  VK_F1,                  XBMCVK_F1,                  "f1")
_add(                 XBMCK_F2,                  VK_F2,                  XBMCVK_F2,                  "f2")
_add(                 XBMCK_F3,                  VK_F3,                  XBMCVK_F3,                  "f3")
_add(                 XBMCK_F4,                  VK_F4,                  XBMCVK_F4,                  "f4")
_add(                 XBMCK_F5,                  VK_F5,                  XBMCVK_F5,                  "f5")
_add(                 XBMCK_F6,                  VK_F6,                  XBMCVK_F6,                  "f6")
_add(                 XBMCK_F7,                  VK_F7,                  XBMCVK_F7,                  "f7")
_add(                 XBMCK_F8,                  VK_F8,                  XBMCVK_F8,                  "f8")
_add(                 XBMCK_F9,                  VK_F9,                  XBMCVK_F9,                  "f9")
_add(                XBMCK_F10,                 VK_F10,                 XBMCVK_F10,                 "f10")
_add(                XBMCK_F11,                 VK_F11,                 XBMCVK_F11,                 "f11")
_add(                XBMCK_F12,                 VK_F12,                 XBMCVK_F12,                 "f12")
_add(                XBMCK_F13,                 VK_F13,                 XBMCVK_F13,                 "f13")
_add(                XBMCK_F14,                 VK_F14,                 XBMCVK_F14,                 "f14")
_add(                XBMCK_F15,                 VK_F15,                 XBMCVK_F15,                 "f15")
_add(                 XBMCK_UP,                  VK_UP,                  XBMCVK_UP,                  "up")
_add(               XBMCK_DOWN,                VK_DOWN,                XBMCVK_DOWN,                "down")
_add(              XBMCK_RIGHT,               VK_RIGHT,               XBMCVK_RIGHT,               "right")
_add(               XBMCK_LEFT,                VK_LEFT,                XBMCVK_LEFT,                "left")
_add(             XBMCK_INSERT,              VK_INSERT,              XBMCVK_INSERT,              "insert")
_add(             XBMCK_DELETE,              VK_DELETE,              XBMCVK_DELETE,              "delete")
_add(               XBMCK_HOME,                VK_HOME,                XBMCVK_HOME,                "home")
_add(                XBMCK_END,                 VK_END,                 XBMCVK_END,                 "end")
_add(             XBMCK_PAGEUP,              VK_PAGEUP,              XBMCVK_PAGEUP,              "pageup")
_add(           XBMCK_PAGEDOWN,            VK_PAGEDOWN,            XBMCVK_PAGEDOWN,            "pagedown")
_add(            XBMCK_NUMLOCK,             VK_NUMLOCK,             XBMCVK_NUMLOCK,             "numlock")
_add(           XBMCK_CAPSLOCK,            VK_CAPSLOCK,            XBMCVK_CAPSLOCK,            "capslock")
_add(             XBMCK_RSHIFT,              VK_RSHIFT,              XBMCVK_RSHIFT,          "rightshift")
_add(             XBMCK_LSHIFT,              VK_LSHIFT,              XBMCVK_LSHIFT,           "leftshift")
_add(              XBMCK_RCTRL,               VK_RCTRL,            XBMCVK_RCONTROL,           "rightctrl")
_add(              XBMCK_LCTRL,               VK_LCTRL,            XBMCVK_LCONTROL,            "leftctrl")
_add(               XBMCK_LALT,                VK_LALT,               XBMCVK_LMENU,             "leftalt")
_add(             XBMCK_LSUPER,              VK_LSUPER,                XBMCVK_LWIN,         "leftwindows")
_add(             XBMCK_RSUPER,              VK_RSUPER,                XBMCVK_RWIN,        "rightwindows")
_add(               XBMCK_MENU,                VK_MENU,                XBMCVK_MENU,                "menu")
_add(              XBMCK_PAUSE,               VK_PAUSE,               XBMCVK_PAUSE,               "pause")
_add(          XBMCK_SCROLLOCK,           VK_SCROLLOCK,          XBMCVK_SCROLLLOCK,          "scrolllock")
_add(              XBMCK_PRINT,               VK_PRINT,         XBMCVK_PRINTSCREEN,         "printscreen")
_add(              XBMCK_POWER,               VK_POWER,               XBMCVK_POWER,               "power")
_add(              XBMCK_SLEEP,               VK_SLEEP,               XBMCVK_SLEEP,               "sleep")
_add(              XBMCK_GUIDE,               VK_GUIDE,               XBMCVK_GUIDE,               "guide")
_add(           XBMCK_SETTINGS,            VK_SETTINGS,            XBMCVK_SETTINGS,            "settings")
_add(               XBMCK_INFO,                VK_INFO,                XBMCVK_INFO,                "info")
_add(                XBMCK_RED,                 VK_RED,                 XBMCVK_RED,                 "red")
_add(              XBMCK_GREEN,               VK_GREEN,               XBMCVK_GREEN,               "green")
_add(             XBMCK_YELLOW,              VK_YELLOW,              XBMCVK_YELLOW,              "yellow")
_add(               XBMCK_BLUE,                VK_BLUE,                XBMCVK_BLUE,                "blue")
_add(               XBMCK_ZOOM,                VK_ZOOM,                XBMCVK_ZOOM,                "zoom")
_add(               XBMCK_TEXT,                VK_TEXT,                XBMCVK_TEXT,                "text")
_add(          XBMCK_FAVORITES,           VK_FAVORITES,           XBMCVK_FAVORITES,           "favorites")
_add(           XBMCK_HOMEPAGE,            VK_HOMEPAGE,            XBMCVK_HOMEPAGE,            "homepage")
_add(             XBMCK_CONFIG,              VK_CONFIG,              XBMCVK_CONFIG,              "config")
_add(                XBMCK_EPG,                 VK_EPG,                 XBMCVK_EPG,                 "epg")